# Generated by Django 2.1.7 on 2019-03-30 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='TaskMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('A', 'Alta'), ('S', 'Sense Prioritat')], default='A', max_length=1, verbose_name='Priority')),
                ('temperature', models.IntegerField(default=0)),
                ('description', models.TextField(default='')),
                ('room', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='StorageAndGo.Room')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='user_maintenance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskOperator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.TextField(default='')),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('A', 'Alta'), ('S', 'Sense Prioritat')], default='A', max_length=1, verbose_name='Priority')),
                ('destination', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='destination', to='StorageAndGo.Room')),
                ('origin', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='origin', to='StorageAndGo.Room')),
                ('quantity', models.ManyToManyField(default='', to='StorageAndGo.Contenidor')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='user_operator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
