# Generated by Django 2.1.7 on 2019-03-29 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='TaskMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('temperature', models.IntegerField(default=0)),
                ('description', models.TextField(default='')),
                ('room', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='StorageAndGo.Room')),
            ],
        ),
        migrations.CreateModel(
            name='TaskOperator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.TextField(default='')),
                ('description', models.TextField()),
                ('destination', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='destination', to='StorageAndGo.Room')),
                ('origin', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='origin', to='StorageAndGo.Room')),
                ('quantity', models.ManyToManyField(default='', to='StorageAndGo.Container')),
            ],
        ),
    ]
