# Generated by Django 2.1.7 on 2019-04-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StorageAndGo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifesto',
            name='reference',
            field=models.BigIntegerField(default='', primary_key=True, serialize=False),
        ),
    ]
