# Generated by Django 2.1.7 on 2019-03-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StorageAndGo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskoperator',
            name='priority',
            field=models.CharField(choices=[('A', 'Alta'), ('M', 'Mitjana'), ('B', 'Baixa')], default='Alta', max_length=1, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='taskmaintenance',
            name='priority',
            field=models.CharField(choices=[('A', 'Alta'), ('M', 'Mitjana'), ('B', 'Baixa')], default='Alta', max_length=1, verbose_name='Priority'),
        ),
    ]
