# Generated by Django 2.1.7 on 2019-06-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StorageAndGo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='hight_priority',
            new_name='high_priority',
        ),
        migrations.AlterField(
            model_name='avaria',
            name='object',
            field=models.TextField(blank=True, default='', verbose_name='Pieza'),
        ),
    ]
