# Generated by Django 2.1.7 on 2019-04-08 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StorageAndGo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, related_name='user_maintenance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskmaintenance',
            name='priority',
            field=models.CharField(blank=True, choices=[('A', 'Alta'), ('S', 'Sense Prioritat')], default='A', max_length=1, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='taskmaintenance',
            name='room',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='StorageAndGo.Room'),
        ),
        migrations.AlterField(
            model_name='taskmaintenance',
            name='temperature',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='taskoperator',
            name='destination',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='destination', to='StorageAndGo.Room'),
        ),
        migrations.AlterField(
            model_name='taskoperator',
            name='origin',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='origin', to='StorageAndGo.Room'),
        ),
        migrations.AlterField(
            model_name='taskoperator',
            name='priority',
            field=models.CharField(blank=True, choices=[('A', 'Alta'), ('S', 'Sense Prioritat')], default='A', max_length=1, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='taskoperator',
            name='product',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='taskoperator',
            name='quantity',
            field=models.ManyToManyField(blank=True, default='', to='StorageAndGo.Contenidor'),
        ),
    ]
