# Generated by Django 2.1.7 on 2019-04-26 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StorageAndGo', '0002_auto_20190426_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenidor',
            name='manifesto',
        ),
    ]
