# Generated by Django 2.1.7 on 2019-05-22 07:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('StorageAndGo', '0002_auto_20190508_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifesto',
            name='Products',
        ),
        migrations.AddField(
            model_name='manifesto',
            name='products',
            field=models.ManyToManyField(related_name='Products', to='StorageAndGo.Contenidor', verbose_name='Productos'),
        ),
        migrations.AlterField(
            model_name='avaria',
            name='object',
            field=models.TextField(blank=True, default='', verbose_name='Objecto'),
        ),
        migrations.AlterField(
            model_name='contenidor',
            name='humidMax',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Humedad máxima'),
        ),
        migrations.AlterField(
            model_name='contenidor',
            name='humidMin',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Humedad mínima'),
        ),
        migrations.AlterField(
            model_name='contenidor',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Nombre contenedor'),
        ),
        migrations.AlterField(
            model_name='contenidor',
            name='qty',
            field=models.IntegerField(null=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='contenidor',
            name='tempMaxDegree',
            field=models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(-30), django.core.validators.MaxValueValidator(30)], verbose_name='Temperatura máxima'),
        ),
        migrations.AlterField(
            model_name='contenidor',
            name='tempMinDegree',
            field=models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(-30), django.core.validators.MaxValueValidator(30)], verbose_name='Temperatura mínima'),
        ),
        migrations.AlterField(
            model_name='manifesto',
            name='creationDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='manifesto',
            name='fromLocation',
            field=models.CharField(max_length=255, verbose_name='Des de'),
        ),
        migrations.AlterField(
            model_name='manifesto',
            name='ref',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='manifesto',
            name='revisionDate',
            field=models.DateTimeField(null=True, verbose_name='Fecha de revisión'),
        ),
        migrations.AlterField(
            model_name='manifesto',
            name='toLocation',
            field=models.CharField(max_length=255, verbose_name='Para'),
        ),
        migrations.AlterField(
            model_name='manifesto',
            name='totalpackets',
            field=models.IntegerField(null=True, verbose_name='Numero total de paquetes'),
        ),
        migrations.AlterField(
            model_name='manifesto',
            name='withdrawal',
            field=models.BooleanField(null=True, verbose_name='Salida'),
        ),
        migrations.AlterField(
            model_name='room',
            name='humitMax',
            field=models.IntegerField(default=0, verbose_name='Humedad máxima'),
        ),
        migrations.AlterField(
            model_name='room',
            name='humitMin',
            field=models.IntegerField(default=0, verbose_name='Humedad mínima'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Nombre sala'),
        ),
        migrations.AlterField(
            model_name='room',
            name='temperatureMax',
            field=models.IntegerField(default=0, verbose_name='Temperatura máxima'),
        ),
        migrations.AlterField(
            model_name='room',
            name='temperatureMin',
            field=models.IntegerField(default=0, verbose_name='Temperatura mínima'),
        ),
        migrations.AlterField(
            model_name='task',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='Acceptado'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(default='', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='task',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Acabado'),
        ),
        migrations.AlterField(
            model_name='task',
            name='hight_priority',
            field=models.BooleanField(default=False, verbose_name='Alta prioridad'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_maintenance', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='taskmaintenance',
            name='temperature',
            field=models.IntegerField(blank=True, default=0, verbose_name='Temperatura'),
        ),
        migrations.AlterField(
            model_name='taskoperator',
            name='destination',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination', to='StorageAndGo.Room', verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='taskoperator',
            name='origin',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='origin', to='StorageAndGo.Room', verbose_name='Origen'),
        ),
        migrations.AlterField(
            model_name='taskoperator',
            name='product',
            field=models.TextField(blank=True, default='', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='taskoperator',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
    ]
