# Generated by Django 2.1.7 on 2019-04-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StorageAndGo', '0002_auto_20190426_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifesto',
            name='reference',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
    ]
