# Generated by Django 2.1.7 on 2019-04-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StorageAndGo', '0003_remove_contenidor_manifesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifesto',
            name='Products',
            field=models.ManyToManyField(null=True, related_name='Products', to='StorageAndGo.Contenidor'),
        ),
    ]
