# Generated by Django 2.1.7 on 2019-04-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StorageAndGo', '0003_auto_20190408_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmaintenance',
            name='priority',
            field=models.CharField(blank=True, choices=[('A', 'Alta'), ('S', 'Sense Prioritat')], max_length=1, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='taskoperator',
            name='priority',
            field=models.CharField(blank=True, choices=[('A', 'Alta'), ('S', 'Sense Prioritat')], max_length=1, verbose_name='Priority'),
        ),
    ]
