# Generated by Django 2.1.7 on 2019-04-28 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StorageAndGo', '0004_auto_20190426_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenidor',
            name='humidMax',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='contenidor',
            name='humidMin',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='contenidor',
            name='tempMaxDegree',
            field=models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(-30), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='contenidor',
            name='tempMinDegree',
            field=models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(-30), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='manifesto',
            name='Products',
            field=models.ManyToManyField(related_name='Products', to='StorageAndGo.Contenidor'),
        ),
    ]
