# Generated by Django 2.1.7 on 2019-04-08 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StorageAndGo', '0004_auto_20190408_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_maintenance', to=settings.AUTH_USER_MODEL),
        ),
    ]
