# Generated by Django 2.1.7 on 2019-04-08 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StorageAndGo', '0005_auto_20190408_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmaintenance',
            name='priority',
            field=models.CharField(blank=True, choices=[('A', 'Alta'), ('S', 'Sense Prioritat')], max_length=1, null=True, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='taskmaintenance',
            name='room',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='StorageAndGo.Room'),
        ),
        migrations.AlterField(
            model_name='taskoperator',
            name='destination',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination', to='StorageAndGo.Room'),
        ),
        migrations.AlterField(
            model_name='taskoperator',
            name='origin',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='origin', to='StorageAndGo.Room'),
        ),
        migrations.AlterField(
            model_name='taskoperator',
            name='quantity',
            field=models.ManyToManyField(blank=True, default='', null=True, to='StorageAndGo.Contenidor'),
        ),
    ]
