# Generated by Django 2.1.7 on 2019-05-02 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StorageAndGo', '0005_auto_20190428_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaria',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='StorageAndGo.Task')),
                ('object', models.TextField(default='')),
                ('room', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='StorageAndGo.Room')),
            ],
            bases=('StorageAndGo.task',),
        ),
    ]
