# Generated by Django 2.1.7 on 2019-04-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StorageAndGo', '0006_auto_20190408_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskoperator',
            name='quantity',
            field=models.ManyToManyField(blank=True, default='', to='StorageAndGo.Contenidor'),
        ),
    ]
