# Generated by Django 2.1.7 on 2019-05-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StorageAndGo', '0006_avaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaria',
            name='object',
            field=models.TextField(blank=True, default=''),
        ),
    ]
