# Generated by Django 2.1.5 on 2019-05-02 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StorageAndGo', '0008_task_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
    ]
