# Generated by Django 2.1.5 on 2019-05-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StorageAndGo', '0009_remove_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='hight_priority',
            field=models.BooleanField(default=False),
        ),
    ]
