# Generated by Django 2.2 on 2019-05-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StorageAndGo', '0011_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='temperatureMin',
            field=models.IntegerField(null=True),
        ),
    ]
