# Generated by Django 2.2 on 2019-05-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StorageAndGo', '0012_room_temperaturemin'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='contenidorsInside',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='humitMax',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='humitMin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='temperatureMax',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='temperatureMin',
            field=models.IntegerField(default=0),
        ),
    ]
