# Generated by Django 2.1.7 on 2019-05-03 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StorageAndGo', '0011_auto_20190502_2033'),
        ('StorageAndGo', '0013_auto_20190502_2120'),
    ]

    operations = [
    ]
