# Generated by Django 2.2 on 2019-05-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StorageAndGo', '0014_merge_20190503_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskoperator',
            name='quantity',
        ),
        migrations.AddField(
            model_name='taskoperator',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
